import { AisleCategory } from '@/api/groceries';

export const productList: { name: string; aisle: AisleCategory }[] = [
  { name: 'Apples', aisle: 'produce' },
  { name: 'Bananas', aisle: 'produce' },
  { name: 'Oranges', aisle: 'produce' },
  { name: 'Lemons', aisle: 'produce' },
  { name: 'Limes', aisle: 'produce' },
  { name: 'Grapes', aisle: 'produce' },
  { name: 'Strawberries', aisle: 'produce' },
  { name: 'Blueberries', aisle: 'produce' },
  { name: 'Raspberries', aisle: 'produce' },
  { name: 'Blackberries', aisle: 'produce' },
  { name: 'Cherries', aisle: 'produce' },
  { name: 'Peaches', aisle: 'produce' },
  { name: 'Nectarines', aisle: 'produce' },
  { name: 'Plums', aisle: 'produce' },
  { name: 'Pears', aisle: 'produce' },
  { name: 'Mangoes', aisle: 'produce' },
  { name: 'Pineapple', aisle: 'produce' },
  { name: 'Watermelon', aisle: 'produce' },
  { name: 'Cantaloupe', aisle: 'produce' },
  { name: 'Honeydew Melon', aisle: 'produce' },
  { name: 'Kiwi', aisle: 'produce' },
  { name: 'Papaya', aisle: 'produce' },
  { name: 'Pomegranate', aisle: 'produce' },
  { name: 'Grapefruit', aisle: 'produce' },
  { name: 'Tangerines', aisle: 'produce' },
  { name: 'Clementines', aisle: 'produce' },
  { name: 'Coconut', aisle: 'produce' },
  { name: 'Avocados', aisle: 'produce' },
  { name: 'Tomatoes', aisle: 'produce' },
  { name: 'Cherry Tomatoes', aisle: 'produce' },
  { name: 'Grape Tomatoes', aisle: 'produce' },
  { name: 'Roma Tomatoes', aisle: 'produce' },
  { name: 'Beefsteak Tomatoes', aisle: 'produce' },
  { name: 'Carrots', aisle: 'produce' },
  { name: 'Baby Carrots', aisle: 'produce' },
  { name: 'Celery', aisle: 'produce' },
  { name: 'Cucumber', aisle: 'produce' },
  { name: 'Bell Peppers', aisle: 'produce' },
  { name: 'Red Bell Pepper', aisle: 'produce' },
  { name: 'Green Bell Pepper', aisle: 'produce' },
  { name: 'Yellow Bell Pepper', aisle: 'produce' },
  { name: 'Orange Bell Pepper', aisle: 'produce' },
  { name: 'Jalapeno Peppers', aisle: 'produce' },
  { name: 'Serrano Peppers', aisle: 'produce' },
  { name: 'Habanero Peppers', aisle: 'produce' },
  { name: 'Poblano Peppers', aisle: 'produce' },
  { name: 'Anaheim Peppers', aisle: 'produce' },
  { name: 'Onions', aisle: 'produce' },
  { name: 'Yellow Onion', aisle: 'produce' },
  { name: 'Red Onion', aisle: 'produce' },
  { name: 'White Onion', aisle: 'produce' },
  { name: 'Sweet Onion', aisle: 'produce' },
  { name: 'Green Onions', aisle: 'produce' },
  { name: 'Shallots', aisle: 'produce' },
  { name: 'Leeks', aisle: 'produce' },
  { name: 'Garlic', aisle: 'produce' },
  { name: 'Ginger', aisle: 'produce' },
  { name: 'Potatoes', aisle: 'produce' },
  { name: 'Russet Potatoes', aisle: 'produce' },
  { name: 'Red Potatoes', aisle: 'produce' },
  { name: 'Yukon Gold Potatoes', aisle: 'produce' },
  { name: 'Fingerling Potatoes', aisle: 'produce' },
  { name: 'Sweet Potatoes', aisle: 'produce' },
  { name: 'Yams', aisle: 'produce' },
  { name: 'Lettuce', aisle: 'produce' },
  { name: 'Romaine Lettuce', aisle: 'produce' },
  { name: 'Iceberg Lettuce', aisle: 'produce' },
  { name: 'Butter Lettuce', aisle: 'produce' },
  { name: 'Mixed Greens', aisle: 'produce' },
  { name: 'Spring Mix', aisle: 'produce' },
  { name: 'Spinach', aisle: 'produce' },
  { name: 'Baby Spinach', aisle: 'produce' },
  { name: 'Arugula', aisle: 'produce' },
  { name: 'Kale', aisle: 'produce' },
  { name: 'Swiss Chard', aisle: 'produce' },
  { name: 'Collard Greens', aisle: 'produce' },
  { name: 'Mustard Greens', aisle: 'produce' },
  { name: 'Cabbage', aisle: 'produce' },
  { name: 'Green Cabbage', aisle: 'produce' },
  { name: 'Red Cabbage', aisle: 'produce' },
  { name: 'Napa Cabbage', aisle: 'produce' },
  { name: 'Bok Choy', aisle: 'produce' },
  { name: 'Brussels Sprouts', aisle: 'produce' },
  { name: 'Broccoli', aisle: 'produce' },
  { name: 'Broccoli Florets', aisle: 'produce' },
  { name: 'Cauliflower', aisle: 'produce' },
  { name: 'Asparagus', aisle: 'produce' },
  { name: 'Green Beans', aisle: 'produce' },
  { name: 'Snow Peas', aisle: 'produce' },
  { name: 'Sugar Snap Peas', aisle: 'produce' },
  { name: 'Zucchini', aisle: 'produce' },
  { name: 'Yellow Squash', aisle: 'produce' },
  { name: 'Butternut Squash', aisle: 'produce' },
  { name: 'Acorn Squash', aisle: 'produce' },
  { name: 'Spaghetti Squash', aisle: 'produce' },
  { name: 'Pumpkin', aisle: 'produce' },
  { name: 'Eggplant', aisle: 'produce' },
  { name: 'Corn on the Cob', aisle: 'produce' },
  { name: 'Mushrooms', aisle: 'produce' },
  { name: 'White Mushrooms', aisle: 'produce' },
  { name: 'Cremini Mushrooms', aisle: 'produce' },
  { name: 'Portobello Mushrooms', aisle: 'produce' },
  { name: 'Shiitake Mushrooms', aisle: 'produce' },
  { name: 'Oyster Mushrooms', aisle: 'produce' },
  { name: 'Radishes', aisle: 'produce' },
  { name: 'Beets', aisle: 'produce' },
  { name: 'Turnips', aisle: 'produce' },
  { name: 'Parsnips', aisle: 'produce' },
  { name: 'Rutabaga', aisle: 'produce' },
  { name: 'Artichokes', aisle: 'produce' },
  { name: 'Fennel', aisle: 'produce' },
  { name: 'Cilantro', aisle: 'produce' },
  { name: 'Parsley', aisle: 'produce' },
  { name: 'Basil', aisle: 'produce' },
  { name: 'Mint', aisle: 'produce' },
  { name: 'Dill', aisle: 'produce' },
  { name: 'Rosemary', aisle: 'produce' },
  { name: 'Thyme', aisle: 'produce' },
  { name: 'Sage', aisle: 'produce' },
  { name: 'Chives', aisle: 'produce' },

  { name: 'White Bread', aisle: 'bakery' },
  { name: 'Whole Wheat Bread', aisle: 'bakery' },
  { name: 'Multigrain Bread', aisle: 'bakery' },
  { name: 'Sourdough Bread', aisle: 'bakery' },
  { name: 'Rye Bread', aisle: 'bakery' },
  { name: 'French Bread', aisle: 'bakery' },
  { name: 'Italian Bread', aisle: 'bakery' },
  { name: 'Ciabatta Bread', aisle: 'bakery' },
  { name: 'Focaccia Bread', aisle: 'bakery' },
  { name: 'Baguette', aisle: 'bakery' },
  { name: 'Bagels', aisle: 'bakery' },
  { name: 'Plain Bagels', aisle: 'bakery' },
  { name: 'Everything Bagels', aisle: 'bakery' },
  { name: 'Sesame Bagels', aisle: 'bakery' },
  { name: 'English Muffins', aisle: 'bakery' },
  { name: 'Croissants', aisle: 'bakery' },
  { name: 'Danish Pastry', aisle: 'bakery' },
  { name: 'Cinnamon Rolls', aisle: 'bakery' },
  { name: 'Donuts', aisle: 'bakery' },
  { name: 'Muffins', aisle: 'bakery' },
  { name: 'Blueberry Muffins', aisle: 'bakery' },
  { name: 'Banana Nut Muffins', aisle: 'bakery' },
  { name: 'Scones', aisle: 'bakery' },
  { name: 'Hamburger Buns', aisle: 'bakery' },
  { name: 'Hot Dog Buns', aisle: 'bakery' },
  { name: 'Dinner Rolls', aisle: 'bakery' },
  { name: 'Kaiser Rolls', aisle: 'bakery' },
  { name: 'Pita Bread', aisle: 'bakery' },
  { name: 'Naan Bread', aisle: 'bakery' },
  { name: 'Flour Tortillas', aisle: 'bakery' },
  { name: 'Corn Tortillas', aisle: 'bakery' },
  { name: 'Wraps', aisle: 'bakery' },
  { name: 'Breadsticks', aisle: 'bakery' },
  { name: 'Garlic Bread', aisle: 'bakery' },
  { name: 'Texas Toast', aisle: 'bakery' },
  { name: 'Brioche', aisle: 'bakery' },
  { name: 'Challah Bread', aisle: 'bakery' },
  { name: 'Cornbread', aisle: 'bakery' },
  { name: 'Banana Bread', aisle: 'bakery' },
  { name: 'Pound Cake', aisle: 'bakery' },

  { name: 'Whole Milk', aisle: 'dairy_eggs' },
  { name: '2% Milk', aisle: 'dairy_eggs' },
  { name: '1% Milk', aisle: 'dairy_eggs' },
  { name: 'Skim Milk', aisle: 'dairy_eggs' },
  { name: 'Half and Half', aisle: 'dairy_eggs' },
  { name: 'Heavy Cream', aisle: 'dairy_eggs' },
  { name: 'Whipping Cream', aisle: 'dairy_eggs' },
  { name: 'Light Cream', aisle: 'dairy_eggs' },
  { name: 'Buttermilk', aisle: 'dairy_eggs' },
  { name: 'Chocolate Milk', aisle: 'dairy_eggs' },
  { name: 'Almond Milk', aisle: 'dairy_eggs' },
  { name: 'Oat Milk', aisle: 'dairy_eggs' },
  { name: 'Soy Milk', aisle: 'dairy_eggs' },
  { name: 'Coconut Milk', aisle: 'dairy_eggs' },
  { name: 'Cashew Milk', aisle: 'dairy_eggs' },
  { name: 'Eggs', aisle: 'dairy_eggs' },
  { name: 'Large Eggs', aisle: 'dairy_eggs' },
  { name: 'Egg Whites', aisle: 'dairy_eggs' },
  { name: 'Butter', aisle: 'dairy_eggs' },
  { name: 'Salted Butter', aisle: 'dairy_eggs' },
  { name: 'Unsalted Butter', aisle: 'dairy_eggs' },
  { name: 'Margarine', aisle: 'dairy_eggs' },
  { name: 'Cheddar Cheese', aisle: 'dairy_eggs' },
  { name: 'Sharp Cheddar Cheese', aisle: 'dairy_eggs' },
  { name: 'Mild Cheddar Cheese', aisle: 'dairy_eggs' },
  { name: 'Mozzarella Cheese', aisle: 'dairy_eggs' },
  { name: 'Fresh Mozzarella', aisle: 'dairy_eggs' },
  { name: 'Parmesan Cheese', aisle: 'dairy_eggs' },
  { name: 'Swiss Cheese', aisle: 'dairy_eggs' },
  { name: 'Provolone Cheese', aisle: 'dairy_eggs' },
  { name: 'Monterey Jack Cheese', aisle: 'dairy_eggs' },
  { name: 'Pepper Jack Cheese', aisle: 'dairy_eggs' },
  { name: 'Colby Jack Cheese', aisle: 'dairy_eggs' },
  { name: 'American Cheese', aisle: 'dairy_eggs' },
  { name: 'Cream Cheese', aisle: 'dairy_eggs' },
  { name: 'Goat Cheese', aisle: 'dairy_eggs' },
  { name: 'Feta Cheese', aisle: 'dairy_eggs' },
  { name: 'Blue Cheese', aisle: 'dairy_eggs' },
  { name: 'Gorgonzola Cheese', aisle: 'dairy_eggs' },
  { name: 'Brie Cheese', aisle: 'dairy_eggs' },
  { name: 'Camembert Cheese', aisle: 'dairy_eggs' },
  { name: 'Ricotta Cheese', aisle: 'dairy_eggs' },
  { name: 'Cottage Cheese', aisle: 'dairy_eggs' },
  { name: 'Mascarpone Cheese', aisle: 'dairy_eggs' },
  { name: 'Shredded Cheese', aisle: 'dairy_eggs' },
  { name: 'Sliced Cheese', aisle: 'dairy_eggs' },
  { name: 'String Cheese', aisle: 'dairy_eggs' },
  { name: 'Yogurt', aisle: 'dairy_eggs' },
  { name: 'Greek Yogurt', aisle: 'dairy_eggs' },
  { name: 'Plain Yogurt', aisle: 'dairy_eggs' },
  { name: 'Vanilla Yogurt', aisle: 'dairy_eggs' },
  { name: 'Sour Cream', aisle: 'dairy_eggs' },
  { name: 'Whipped Cream', aisle: 'dairy_eggs' },
  { name: 'Cool Whip', aisle: 'dairy_eggs' },
  { name: 'Coffee Creamer', aisle: 'dairy_eggs' },
  { name: 'Eggnog', aisle: 'dairy_eggs' },

  { name: 'Chicken Breast', aisle: 'meat' },
  { name: 'Boneless Skinless Chicken Breast', aisle: 'meat' },
  { name: 'Chicken Thighs', aisle: 'meat' },
  { name: 'Boneless Skinless Chicken Thighs', aisle: 'meat' },
  { name: 'Chicken Drumsticks', aisle: 'meat' },
  { name: 'Chicken Wings', aisle: 'meat' },
  { name: 'Whole Chicken', aisle: 'meat' },
  { name: 'Chicken Tenders', aisle: 'meat' },
  { name: 'Ground Chicken', aisle: 'meat' },
  { name: 'Turkey Breast', aisle: 'meat' },
  { name: 'Ground Turkey', aisle: 'meat' },
  { name: 'Turkey Bacon', aisle: 'meat' },
  { name: 'Turkey Sausage', aisle: 'meat' },
  { name: 'Whole Turkey', aisle: 'meat' },
  { name: 'Duck', aisle: 'meat' },
  { name: 'Ground Beef', aisle: 'meat' },
  { name: 'Lean Ground Beef', aisle: 'meat' },
  { name: 'Beef Steak', aisle: 'meat' },
  { name: 'Ribeye Steak', aisle: 'meat' },
  { name: 'New York Strip Steak', aisle: 'meat' },
  { name: 'Sirloin Steak', aisle: 'meat' },
  { name: 'Filet Mignon', aisle: 'meat' },
  { name: 'T-Bone Steak', aisle: 'meat' },
  { name: 'Flank Steak', aisle: 'meat' },
  { name: 'Skirt Steak', aisle: 'meat' },
  { name: 'Beef Roast', aisle: 'meat' },
  { name: 'Chuck Roast', aisle: 'meat' },
  { name: 'Beef Brisket', aisle: 'meat' },
  { name: 'Beef Short Ribs', aisle: 'meat' },
  { name: 'Beef Stew Meat', aisle: 'meat' },
  { name: 'Corned Beef', aisle: 'meat' },
  { name: 'Pork Chops', aisle: 'meat' },
  { name: 'Boneless Pork Chops', aisle: 'meat' },
  { name: 'Pork Tenderloin', aisle: 'meat' },
  { name: 'Pork Loin', aisle: 'meat' },
  { name: 'Pork Shoulder', aisle: 'meat' },
  { name: 'Pork Ribs', aisle: 'meat' },
  { name: 'Baby Back Ribs', aisle: 'meat' },
  { name: 'Spare Ribs', aisle: 'meat' },
  { name: 'Ground Pork', aisle: 'meat' },
  { name: 'Pork Belly', aisle: 'meat' },
  { name: 'Ham', aisle: 'meat' },
  { name: 'Sliced Ham', aisle: 'meat' },
  { name: 'Ham Steak', aisle: 'meat' },
  { name: 'Bacon', aisle: 'meat' },
  { name: 'Thick Cut Bacon', aisle: 'meat' },
  { name: 'Canadian Bacon', aisle: 'meat' },
  { name: 'Pancetta', aisle: 'meat' },
  { name: 'Prosciutto', aisle: 'meat' },
  { name: 'Sausage', aisle: 'meat' },
  { name: 'Italian Sausage', aisle: 'meat' },
  { name: 'Breakfast Sausage', aisle: 'meat' },
  { name: 'Bratwurst', aisle: 'meat' },
  { name: 'Kielbasa', aisle: 'meat' },
  { name: 'Chorizo', aisle: 'meat' },
  { name: 'Andouille Sausage', aisle: 'meat' },
  { name: 'Hot Dogs', aisle: 'meat' },
  { name: 'Lamb Chops', aisle: 'meat' },
  { name: 'Lamb Leg', aisle: 'meat' },
  { name: 'Ground Lamb', aisle: 'meat' },
  { name: 'Lamb Shoulder', aisle: 'meat' },
  { name: 'Veal', aisle: 'meat' },
  { name: 'Deli Turkey', aisle: 'meat' },
  { name: 'Deli Ham', aisle: 'meat' },
  { name: 'Deli Roast Beef', aisle: 'meat' },
  { name: 'Salami', aisle: 'meat' },
  { name: 'Pepperoni', aisle: 'meat' },
  { name: 'Bologna', aisle: 'meat' },
  { name: 'Pastrami', aisle: 'meat' },
  { name: 'Liverwurst', aisle: 'meat' },

  { name: 'Salmon Fillet', aisle: 'seafood' },
  { name: 'Atlantic Salmon', aisle: 'seafood' },
  { name: 'Sockeye Salmon', aisle: 'seafood' },
  { name: 'Smoked Salmon', aisle: 'seafood' },
  { name: 'Tuna Steak', aisle: 'seafood' },
  { name: 'Ahi Tuna', aisle: 'seafood' },
  { name: 'Cod Fillet', aisle: 'seafood' },
  { name: 'Tilapia Fillet', aisle: 'seafood' },
  { name: 'Halibut', aisle: 'seafood' },
  { name: 'Mahi Mahi', aisle: 'seafood' },
  { name: 'Sea Bass', aisle: 'seafood' },
  { name: 'Snapper', aisle: 'seafood' },
  { name: 'Trout', aisle: 'seafood' },
  { name: 'Catfish', aisle: 'seafood' },
  { name: 'Swordfish', aisle: 'seafood' },
  { name: 'Flounder', aisle: 'seafood' },
  { name: 'Sole', aisle: 'seafood' },
  { name: 'Haddock', aisle: 'seafood' },
  { name: 'Perch', aisle: 'seafood' },
  { name: 'Sardines', aisle: 'seafood' },
  { name: 'Anchovies', aisle: 'seafood' },
  { name: 'Shrimp', aisle: 'seafood' },
  { name: 'Large Shrimp', aisle: 'seafood' },
  { name: 'Jumbo Shrimp', aisle: 'seafood' },
  { name: 'Cooked Shrimp', aisle: 'seafood' },
  { name: 'Cocktail Shrimp', aisle: 'seafood' },
  { name: 'Crab', aisle: 'seafood' },
  { name: 'Crab Legs', aisle: 'seafood' },
  { name: 'Crab Meat', aisle: 'seafood' },
  { name: 'Imitation Crab', aisle: 'seafood' },
  { name: 'Lobster', aisle: 'seafood' },
  { name: 'Lobster Tail', aisle: 'seafood' },
  { name: 'Scallops', aisle: 'seafood' },
  { name: 'Sea Scallops', aisle: 'seafood' },
  { name: 'Bay Scallops', aisle: 'seafood' },
  { name: 'Clams', aisle: 'seafood' },
  { name: 'Mussels', aisle: 'seafood' },
  { name: 'Oysters', aisle: 'seafood' },
  { name: 'Calamari', aisle: 'seafood' },
  { name: 'Squid', aisle: 'seafood' },
  { name: 'Octopus', aisle: 'seafood' },
  { name: 'Crawfish', aisle: 'seafood' },

  { name: 'Spaghetti', aisle: 'pantry' },
  { name: 'Penne', aisle: 'pantry' },
  { name: 'Rigatoni', aisle: 'pantry' },
  { name: 'Fusilli', aisle: 'pantry' },
  { name: 'Farfalle', aisle: 'pantry' },
  { name: 'Rotini', aisle: 'pantry' },
  { name: 'Linguine', aisle: 'pantry' },
  { name: 'Fettuccine', aisle: 'pantry' },
  { name: 'Angel Hair Pasta', aisle: 'pantry' },
  { name: 'Lasagna Noodles', aisle: 'pantry' },
  { name: 'Macaroni', aisle: 'pantry' },
  { name: 'Elbow Macaroni', aisle: 'pantry' },
  { name: 'Orzo', aisle: 'pantry' },
  { name: 'Egg Noodles', aisle: 'pantry' },
  { name: 'Rice Noodles', aisle: 'pantry' },
  { name: 'Ramen Noodles', aisle: 'pantry' },
  { name: 'Udon Noodles', aisle: 'pantry' },
  { name: 'Soba Noodles', aisle: 'pantry' },
  { name: 'White Rice', aisle: 'pantry' },
  { name: 'Brown Rice', aisle: 'pantry' },
  { name: 'Jasmine Rice', aisle: 'pantry' },
  { name: 'Basmati Rice', aisle: 'pantry' },
  { name: 'Arborio Rice', aisle: 'pantry' },
  { name: 'Wild Rice', aisle: 'pantry' },
  { name: 'Instant Rice', aisle: 'pantry' },
  { name: 'Quinoa', aisle: 'pantry' },
  { name: 'Couscous', aisle: 'pantry' },
  { name: 'Bulgur', aisle: 'pantry' },
  { name: 'Farro', aisle: 'pantry' },
  { name: 'Barley', aisle: 'pantry' },
  { name: 'Oats', aisle: 'pantry' },
  { name: 'Rolled Oats', aisle: 'pantry' },
  { name: 'Steel Cut Oats', aisle: 'pantry' },
  { name: 'Instant Oatmeal', aisle: 'pantry' },
  { name: 'Cereal', aisle: 'pantry' },
  { name: 'Corn Flakes', aisle: 'pantry' },
  { name: 'Granola', aisle: 'pantry' },
  { name: 'Muesli', aisle: 'pantry' },
  { name: 'Canned Tomatoes', aisle: 'pantry' },
  { name: 'Diced Tomatoes', aisle: 'pantry' },
  { name: 'Crushed Tomatoes', aisle: 'pantry' },
  { name: 'Tomato Sauce', aisle: 'pantry' },
  { name: 'Tomato Paste', aisle: 'pantry' },
  { name: 'Sun-Dried Tomatoes', aisle: 'pantry' },
  { name: 'Canned Corn', aisle: 'pantry' },
  { name: 'Canned Green Beans', aisle: 'pantry' },
  { name: 'Canned Peas', aisle: 'pantry' },
  { name: 'Canned Carrots', aisle: 'pantry' },
  { name: 'Canned Mushrooms', aisle: 'pantry' },
  { name: 'Canned Olives', aisle: 'pantry' },
  { name: 'Black Olives', aisle: 'pantry' },
  { name: 'Green Olives', aisle: 'pantry' },
  { name: 'Kalamata Olives', aisle: 'pantry' },
  { name: 'Canned Artichoke Hearts', aisle: 'pantry' },
  { name: 'Roasted Red Peppers', aisle: 'pantry' },
  { name: 'Canned Black Beans', aisle: 'pantry' },
  { name: 'Canned Kidney Beans', aisle: 'pantry' },
  { name: 'Canned Pinto Beans', aisle: 'pantry' },
  { name: 'Canned Chickpeas', aisle: 'pantry' },
  { name: 'Canned Cannellini Beans', aisle: 'pantry' },
  { name: 'Canned Navy Beans', aisle: 'pantry' },
  { name: 'Canned Refried Beans', aisle: 'pantry' },
  { name: 'Baked Beans', aisle: 'pantry' },
  { name: 'Canned Lentils', aisle: 'pantry' },
  { name: 'Dried Black Beans', aisle: 'pantry' },
  { name: 'Dried Lentils', aisle: 'pantry' },
  { name: 'Red Lentils', aisle: 'pantry' },
  { name: 'Green Lentils', aisle: 'pantry' },
  { name: 'Split Peas', aisle: 'pantry' },
  { name: 'Canned Tuna', aisle: 'pantry' },
  { name: 'Canned Salmon', aisle: 'pantry' },
  { name: 'Canned Sardines', aisle: 'pantry' },
  { name: 'Canned Chicken', aisle: 'pantry' },
  { name: 'Spam', aisle: 'pantry' },
  { name: 'Chicken Broth', aisle: 'pantry' },
  { name: 'Beef Broth', aisle: 'pantry' },
  { name: 'Vegetable Broth', aisle: 'pantry' },
  { name: 'Chicken Stock', aisle: 'pantry' },
  { name: 'Beef Stock', aisle: 'pantry' },
  { name: 'Canned Soup', aisle: 'pantry' },
  { name: 'Cream of Mushroom Soup', aisle: 'pantry' },
  { name: 'Cream of Chicken Soup', aisle: 'pantry' },
  { name: 'Tomato Soup', aisle: 'pantry' },
  { name: 'Chicken Noodle Soup', aisle: 'pantry' },
  { name: 'Vegetable Oil', aisle: 'pantry' },
  { name: 'Olive Oil', aisle: 'pantry' },
  { name: 'Extra Virgin Olive Oil', aisle: 'pantry' },
  { name: 'Canola Oil', aisle: 'pantry' },
  { name: 'Coconut Oil', aisle: 'pantry' },
  { name: 'Sesame Oil', aisle: 'pantry' },
  { name: 'Avocado Oil', aisle: 'pantry' },
  { name: 'Peanut Oil', aisle: 'pantry' },
  { name: 'Vegetable Shortening', aisle: 'pantry' },
  { name: 'Cooking Spray', aisle: 'pantry' },
  { name: 'White Vinegar', aisle: 'pantry' },
  { name: 'Apple Cider Vinegar', aisle: 'pantry' },
  { name: 'Balsamic Vinegar', aisle: 'pantry' },
  { name: 'Red Wine Vinegar', aisle: 'pantry' },
  { name: 'Rice Vinegar', aisle: 'pantry' },
  { name: 'Peanut Butter', aisle: 'pantry' },
  { name: 'Creamy Peanut Butter', aisle: 'pantry' },
  { name: 'Crunchy Peanut Butter', aisle: 'pantry' },
  { name: 'Almond Butter', aisle: 'pantry' },
  { name: 'Cashew Butter', aisle: 'pantry' },
  { name: 'Nutella', aisle: 'pantry' },
  { name: 'Jelly', aisle: 'pantry' },
  { name: 'Grape Jelly', aisle: 'pantry' },
  { name: 'Strawberry Jam', aisle: 'pantry' },
  { name: 'Raspberry Jam', aisle: 'pantry' },
  { name: 'Orange Marmalade', aisle: 'pantry' },
  { name: 'Honey', aisle: 'pantry' },
  { name: 'Maple Syrup', aisle: 'pantry' },
  { name: 'Pancake Syrup', aisle: 'pantry' },
  { name: 'Agave Nectar', aisle: 'pantry' },
  { name: 'Molasses', aisle: 'pantry' },
  { name: 'Corn Syrup', aisle: 'pantry' },
  { name: 'Breadcrumbs', aisle: 'pantry' },
  { name: 'Panko Breadcrumbs', aisle: 'pantry' },
  { name: 'Croutons', aisle: 'pantry' },
  { name: 'Stuffing Mix', aisle: 'pantry' },
  { name: 'Raisins', aisle: 'pantry' },
  { name: 'Dried Cranberries', aisle: 'pantry' },
  { name: 'Dried Apricots', aisle: 'pantry' },
  { name: 'Dried Figs', aisle: 'pantry' },
  { name: 'Dates', aisle: 'pantry' },
  { name: 'Prunes', aisle: 'pantry' },
  { name: 'Canned Pineapple', aisle: 'pantry' },
  { name: 'Canned Peaches', aisle: 'pantry' },
  { name: 'Canned Pears', aisle: 'pantry' },
  { name: 'Canned Mandarin Oranges', aisle: 'pantry' },
  { name: 'Canned Fruit Cocktail', aisle: 'pantry' },
  { name: 'Applesauce', aisle: 'pantry' },
  { name: 'Canned Pumpkin', aisle: 'pantry' },
  { name: 'Coconut Milk', aisle: 'pantry' },
  { name: 'Evaporated Milk', aisle: 'pantry' },
  { name: 'Sweetened Condensed Milk', aisle: 'pantry' },
  { name: 'Powdered Milk', aisle: 'pantry' },

  { name: 'Frozen Pizza', aisle: 'frozen_foods' },
  { name: 'Frozen Pepperoni Pizza', aisle: 'frozen_foods' },
  { name: 'Frozen Cheese Pizza', aisle: 'frozen_foods' },
  { name: 'Pizza Rolls', aisle: 'frozen_foods' },
  { name: 'Hot Pockets', aisle: 'frozen_foods' },
  { name: 'Frozen Burritos', aisle: 'frozen_foods' },
  { name: 'Frozen Lasagna', aisle: 'frozen_foods' },
  { name: 'TV Dinners', aisle: 'frozen_foods' },
  { name: 'Frozen Mac and Cheese', aisle: 'frozen_foods' },
  { name: 'Frozen Chicken Nuggets', aisle: 'frozen_foods' },
  { name: 'Frozen Chicken Tenders', aisle: 'frozen_foods' },
  { name: 'Frozen Chicken Wings', aisle: 'frozen_foods' },
  { name: 'Frozen Fish Sticks', aisle: 'frozen_foods' },
  { name: 'Frozen Fish Fillets', aisle: 'frozen_foods' },
  { name: 'Frozen Shrimp', aisle: 'frozen_foods' },
  { name: 'Frozen Meatballs', aisle: 'frozen_foods' },
  { name: 'Frozen Hamburger Patties', aisle: 'frozen_foods' },
  { name: 'Frozen Breakfast Sandwiches', aisle: 'frozen_foods' },
  { name: 'Frozen Pancakes', aisle: 'frozen_foods' },
  { name: 'Frozen Waffles', aisle: 'frozen_foods' },
  { name: 'Frozen French Toast', aisle: 'frozen_foods' },
  { name: 'Frozen Hash Browns', aisle: 'frozen_foods' },
  { name: 'Frozen Tater Tots', aisle: 'frozen_foods' },
  { name: 'Frozen French Fries', aisle: 'frozen_foods' },
  { name: 'Frozen Onion Rings', aisle: 'frozen_foods' },
  { name: 'Frozen Mozzarella Sticks', aisle: 'frozen_foods' },
  { name: 'Frozen Egg Rolls', aisle: 'frozen_foods' },
  { name: 'Frozen Dumplings', aisle: 'frozen_foods' },
  { name: 'Frozen Potstickers', aisle: 'frozen_foods' },
  { name: 'Frozen Spring Rolls', aisle: 'frozen_foods' },
  { name: 'Frozen Peas', aisle: 'frozen_foods' },
  { name: 'Frozen Corn', aisle: 'frozen_foods' },
  { name: 'Frozen Green Beans', aisle: 'frozen_foods' },
  { name: 'Frozen Broccoli', aisle: 'frozen_foods' },
  { name: 'Frozen Cauliflower', aisle: 'frozen_foods' },
  { name: 'Frozen Spinach', aisle: 'frozen_foods' },
  { name: 'Frozen Mixed Vegetables', aisle: 'frozen_foods' },
  { name: 'Frozen Stir Fry Vegetables', aisle: 'frozen_foods' },
  { name: 'Frozen Edamame', aisle: 'frozen_foods' },
  { name: 'Frozen Lima Beans', aisle: 'frozen_foods' },
  { name: 'Frozen Brussels Sprouts', aisle: 'frozen_foods' },
  { name: 'Frozen Okra', aisle: 'frozen_foods' },
  { name: 'Frozen Strawberries', aisle: 'frozen_foods' },
  { name: 'Frozen Blueberries', aisle: 'frozen_foods' },
  { name: 'Frozen Raspberries', aisle: 'frozen_foods' },
  { name: 'Frozen Mixed Berries', aisle: 'frozen_foods' },
  { name: 'Frozen Mango', aisle: 'frozen_foods' },
  { name: 'Frozen Peaches', aisle: 'frozen_foods' },
  { name: 'Frozen Cherries', aisle: 'frozen_foods' },
  { name: 'Frozen Pineapple', aisle: 'frozen_foods' },
  { name: 'Frozen Acai', aisle: 'frozen_foods' },
  { name: 'Ice Cream', aisle: 'frozen_foods' },
  { name: 'Vanilla Ice Cream', aisle: 'frozen_foods' },
  { name: 'Chocolate Ice Cream', aisle: 'frozen_foods' },
  { name: 'Strawberry Ice Cream', aisle: 'frozen_foods' },
  { name: 'Ice Cream Sandwiches', aisle: 'frozen_foods' },
  { name: 'Ice Cream Bars', aisle: 'frozen_foods' },
  { name: 'Popsicles', aisle: 'frozen_foods' },
  { name: 'Frozen Yogurt', aisle: 'frozen_foods' },
  { name: 'Sorbet', aisle: 'frozen_foods' },
  { name: 'Gelato', aisle: 'frozen_foods' },
  { name: 'Frozen Pie', aisle: 'frozen_foods' },
  { name: 'Frozen Pie Crust', aisle: 'frozen_foods' },
  { name: 'Frozen Cheesecake', aisle: 'frozen_foods' },
  { name: 'Frozen Cookie Dough', aisle: 'frozen_foods' },
  { name: 'Frozen Bread Dough', aisle: 'frozen_foods' },
  { name: 'Frozen Biscuits', aisle: 'frozen_foods' },
  { name: 'Frozen Croissants', aisle: 'frozen_foods' },
  { name: 'Frozen Puff Pastry', aisle: 'frozen_foods' },
  { name: 'Frozen Phyllo Dough', aisle: 'frozen_foods' },

  { name: 'Orange Juice', aisle: 'beverages' },
  { name: 'Apple Juice', aisle: 'beverages' },
  { name: 'Grape Juice', aisle: 'beverages' },
  { name: 'Cranberry Juice', aisle: 'beverages' },
  { name: 'Grapefruit Juice', aisle: 'beverages' },
  { name: 'Pineapple Juice', aisle: 'beverages' },
  { name: 'Tomato Juice', aisle: 'beverages' },
  { name: 'V8 Juice', aisle: 'beverages' },
  { name: 'Lemonade', aisle: 'beverages' },
  { name: 'Iced Tea', aisle: 'beverages' },
  { name: 'Sweet Tea', aisle: 'beverages' },
  { name: 'Green Tea', aisle: 'beverages' },
  { name: 'Black Tea', aisle: 'beverages' },
  { name: 'Herbal Tea', aisle: 'beverages' },
  { name: 'Chamomile Tea', aisle: 'beverages' },
  { name: 'Earl Grey Tea', aisle: 'beverages' },
  { name: 'English Breakfast Tea', aisle: 'beverages' },
  { name: 'Coffee', aisle: 'beverages' },
  { name: 'Ground Coffee', aisle: 'beverages' },
  { name: 'Whole Bean Coffee', aisle: 'beverages' },
  { name: 'Instant Coffee', aisle: 'beverages' },
  { name: 'Decaf Coffee', aisle: 'beverages' },
  { name: 'Coffee Pods', aisle: 'beverages' },
  { name: 'Espresso', aisle: 'beverages' },
  { name: 'Cold Brew Coffee', aisle: 'beverages' },
  { name: 'Hot Chocolate Mix', aisle: 'beverages' },
  { name: 'Coca-Cola', aisle: 'beverages' },
  { name: 'Pepsi', aisle: 'beverages' },
  { name: 'Sprite', aisle: 'beverages' },
  { name: '7-Up', aisle: 'beverages' },
  { name: 'Mountain Dew', aisle: 'beverages' },
  { name: 'Dr Pepper', aisle: 'beverages' },
  { name: 'Root Beer', aisle: 'beverages' },
  { name: 'Ginger Ale', aisle: 'beverages' },
  { name: 'Club Soda', aisle: 'beverages' },
  { name: 'Tonic Water', aisle: 'beverages' },
  { name: 'Sparkling Water', aisle: 'beverages' },
  { name: 'Seltzer Water', aisle: 'beverages' },
  { name: 'Bottled Water', aisle: 'beverages' },
  { name: 'Sports Drinks', aisle: 'beverages' },
  { name: 'Gatorade', aisle: 'beverages' },
  { name: 'Energy Drinks', aisle: 'beverages' },
  { name: 'Red Bull', aisle: 'beverages' },
  { name: 'Monster Energy', aisle: 'beverages' },
  { name: 'Coconut Water', aisle: 'beverages' },
  { name: 'Kombucha', aisle: 'beverages' },
  { name: 'Smoothie Mix', aisle: 'beverages' },
  { name: 'Protein Shake', aisle: 'beverages' },
  { name: 'Aloe Vera Juice', aisle: 'beverages' },

  { name: 'Potato Chips', aisle: 'snacks' },
  { name: 'Tortilla Chips', aisle: 'snacks' },
  { name: 'Corn Chips', aisle: 'snacks' },
  { name: 'Doritos', aisle: 'snacks' },
  { name: 'Cheetos', aisle: 'snacks' },
  { name: 'Pringles', aisle: 'snacks' },
  { name: 'Fritos', aisle: 'snacks' },
  { name: 'Sun Chips', aisle: 'snacks' },
  { name: 'Kettle Chips', aisle: 'snacks' },
  { name: 'Veggie Chips', aisle: 'snacks' },
  { name: 'Popcorn', aisle: 'snacks' },
  { name: 'Microwave Popcorn', aisle: 'snacks' },
  { name: 'Popcorn Kernels', aisle: 'snacks' },
  { name: 'Pretzels', aisle: 'snacks' },
  { name: 'Pretzel Sticks', aisle: 'snacks' },
  { name: 'Pretzel Twists', aisle: 'snacks' },
  { name: 'Crackers', aisle: 'snacks' },
  { name: 'Saltine Crackers', aisle: 'snacks' },
  { name: 'Ritz Crackers', aisle: 'snacks' },
  { name: 'Graham Crackers', aisle: 'snacks' },
  { name: 'Goldfish Crackers', aisle: 'snacks' },
  { name: 'Cheese Crackers', aisle: 'snacks' },
  { name: 'Animal Crackers', aisle: 'snacks' },
  { name: 'Rice Cakes', aisle: 'snacks' },
  { name: 'Granola Bars', aisle: 'snacks' },
  { name: 'Protein Bars', aisle: 'snacks' },
  { name: 'Energy Bars', aisle: 'snacks' },
  { name: 'Fruit Snacks', aisle: 'snacks' },
  { name: 'Gummy Bears', aisle: 'snacks' },
  { name: 'Gummy Worms', aisle: 'snacks' },
  { name: 'Licorice', aisle: 'snacks' },
  { name: 'Candy Bars', aisle: 'snacks' },
  { name: 'Chocolate Bar', aisle: 'snacks' },
  { name: 'Dark Chocolate', aisle: 'snacks' },
  { name: 'Milk Chocolate', aisle: 'snacks' },
  { name: 'White Chocolate', aisle: 'snacks' },
  { name: 'Chocolate Chips', aisle: 'snacks' },
  { name: 'M&Ms', aisle: 'snacks' },
  { name: 'Reeses Cups', aisle: 'snacks' },
  { name: 'Snickers', aisle: 'snacks' },
  { name: 'Skittles', aisle: 'snacks' },
  { name: 'Starburst', aisle: 'snacks' },
  { name: 'Jolly Ranchers', aisle: 'snacks' },
  { name: 'Lollipops', aisle: 'snacks' },
  { name: 'Hard Candy', aisle: 'snacks' },
  { name: 'Mints', aisle: 'snacks' },
  { name: 'Chewing Gum', aisle: 'snacks' },
  { name: 'Trail Mix', aisle: 'snacks' },
  { name: 'Mixed Nuts', aisle: 'snacks' },
  { name: 'Peanuts', aisle: 'snacks' },
  { name: 'Almonds', aisle: 'snacks' },
  { name: 'Cashews', aisle: 'snacks' },
  { name: 'Walnuts', aisle: 'snacks' },
  { name: 'Pecans', aisle: 'snacks' },
  { name: 'Pistachios', aisle: 'snacks' },
  { name: 'Macadamia Nuts', aisle: 'snacks' },
  { name: 'Hazelnuts', aisle: 'snacks' },
  { name: 'Sunflower Seeds', aisle: 'snacks' },
  { name: 'Pumpkin Seeds', aisle: 'snacks' },
  { name: 'Beef Jerky', aisle: 'snacks' },
  { name: 'Turkey Jerky', aisle: 'snacks' },
  { name: 'Dried Fruit', aisle: 'snacks' },
  { name: 'Fruit Leather', aisle: 'snacks' },
  { name: 'Cookies', aisle: 'snacks' },
  { name: 'Chocolate Chip Cookies', aisle: 'snacks' },
  { name: 'Oreos', aisle: 'snacks' },
  { name: 'Fig Newtons', aisle: 'snacks' },
  { name: 'Brownies', aisle: 'snacks' },
  { name: 'Rice Krispies Treats', aisle: 'snacks' },
  { name: 'Pudding Cups', aisle: 'snacks' },
  { name: 'Jello Cups', aisle: 'snacks' },
  { name: 'Applesauce Cups', aisle: 'snacks' },
  { name: 'Hummus', aisle: 'snacks' },
  { name: 'Guacamole', aisle: 'snacks' },
  { name: 'Salsa', aisle: 'snacks' },
  { name: 'Queso Dip', aisle: 'snacks' },
  { name: 'French Onion Dip', aisle: 'snacks' },
  { name: 'Spinach Artichoke Dip', aisle: 'snacks' },

  { name: 'Ketchup', aisle: 'condiments_sauces' },
  { name: 'Mustard', aisle: 'condiments_sauces' },
  { name: 'Yellow Mustard', aisle: 'condiments_sauces' },
  { name: 'Dijon Mustard', aisle: 'condiments_sauces' },
  { name: 'Spicy Brown Mustard', aisle: 'condiments_sauces' },
  { name: 'Honey Mustard', aisle: 'condiments_sauces' },
  { name: 'Mayonnaise', aisle: 'condiments_sauces' },
  { name: 'Light Mayonnaise', aisle: 'condiments_sauces' },
  { name: 'Miracle Whip', aisle: 'condiments_sauces' },
  { name: 'Relish', aisle: 'condiments_sauces' },
  { name: 'Sweet Relish', aisle: 'condiments_sauces' },
  { name: 'Dill Relish', aisle: 'condiments_sauces' },
  { name: 'Pickles', aisle: 'condiments_sauces' },
  { name: 'Dill Pickles', aisle: 'condiments_sauces' },
  { name: 'Bread and Butter Pickles', aisle: 'condiments_sauces' },
  { name: 'Pickle Spears', aisle: 'condiments_sauces' },
  { name: 'Hot Sauce', aisle: 'condiments_sauces' },
  { name: 'Tabasco', aisle: 'condiments_sauces' },
  { name: 'Sriracha', aisle: 'condiments_sauces' },
  { name: 'Cholula', aisle: 'condiments_sauces' },
  { name: "Frank's Red Hot", aisle: 'condiments_sauces' },
  { name: 'BBQ Sauce', aisle: 'condiments_sauces' },
  { name: 'Honey BBQ Sauce', aisle: 'condiments_sauces' },
  { name: 'Steak Sauce', aisle: 'condiments_sauces' },
  { name: 'A1 Sauce', aisle: 'condiments_sauces' },
  { name: 'Worcestershire Sauce', aisle: 'condiments_sauces' },
  { name: 'Soy Sauce', aisle: 'condiments_sauces' },
  { name: 'Low Sodium Soy Sauce', aisle: 'condiments_sauces' },
  { name: 'Tamari', aisle: 'condiments_sauces' },
  { name: 'Teriyaki Sauce', aisle: 'condiments_sauces' },
  { name: 'Hoisin Sauce', aisle: 'condiments_sauces' },
  { name: 'Oyster Sauce', aisle: 'condiments_sauces' },
  { name: 'Fish Sauce', aisle: 'condiments_sauces' },
  { name: 'Sweet Chili Sauce', aisle: 'condiments_sauces' },
  { name: 'Duck Sauce', aisle: 'condiments_sauces' },
  { name: 'Plum Sauce', aisle: 'condiments_sauces' },
  { name: 'Peanut Sauce', aisle: 'condiments_sauces' },
  { name: 'Pasta Sauce', aisle: 'condiments_sauces' },
  { name: 'Marinara Sauce', aisle: 'condiments_sauces' },
  { name: 'Tomato Basil Sauce', aisle: 'condiments_sauces' },
  { name: 'Alfredo Sauce', aisle: 'condiments_sauces' },
  { name: 'Pesto Sauce', aisle: 'condiments_sauces' },
  { name: 'Vodka Sauce', aisle: 'condiments_sauces' },
  { name: 'Pizza Sauce', aisle: 'condiments_sauces' },
  { name: 'Enchilada Sauce', aisle: 'condiments_sauces' },
  { name: 'Green Enchilada Sauce', aisle: 'condiments_sauces' },
  { name: 'Red Enchilada Sauce', aisle: 'condiments_sauces' },
  { name: 'Taco Sauce', aisle: 'condiments_sauces' },
  { name: 'Salsa Verde', aisle: 'condiments_sauces' },
  { name: 'Chipotle Peppers in Adobo', aisle: 'condiments_sauces' },
  { name: 'Green Chiles', aisle: 'condiments_sauces' },
  { name: 'Jalapenos', aisle: 'condiments_sauces' },
  { name: 'Ranch Dressing', aisle: 'condiments_sauces' },
  { name: 'Italian Dressing', aisle: 'condiments_sauces' },
  { name: 'Caesar Dressing', aisle: 'condiments_sauces' },
  { name: 'Blue Cheese Dressing', aisle: 'condiments_sauces' },
  { name: 'Thousand Island Dressing', aisle: 'condiments_sauces' },
  { name: 'French Dressing', aisle: 'condiments_sauces' },
  { name: 'Balsamic Vinaigrette', aisle: 'condiments_sauces' },
  { name: 'Greek Dressing', aisle: 'condiments_sauces' },
  { name: 'Honey Mustard Dressing', aisle: 'condiments_sauces' },
  { name: 'Asian Sesame Dressing', aisle: 'condiments_sauces' },
  { name: 'Tartar Sauce', aisle: 'condiments_sauces' },
  { name: 'Cocktail Sauce', aisle: 'condiments_sauces' },
  { name: 'Horseradish', aisle: 'condiments_sauces' },
  { name: 'Wasabi', aisle: 'condiments_sauces' },
  { name: 'Capers', aisle: 'condiments_sauces' },
  { name: 'Anchovy Paste', aisle: 'condiments_sauces' },
  { name: 'Tahini', aisle: 'condiments_sauces' },
  { name: 'Miso Paste', aisle: 'condiments_sauces' },
  { name: 'Curry Paste', aisle: 'condiments_sauces' },
  { name: 'Red Curry Paste', aisle: 'condiments_sauces' },
  { name: 'Green Curry Paste', aisle: 'condiments_sauces' },
  { name: 'Harissa', aisle: 'condiments_sauces' },
  { name: 'Sambal Oelek', aisle: 'condiments_sauces' },
  { name: 'Gochujang', aisle: 'condiments_sauces' },

  { name: 'Salt', aisle: 'spices_baking' },
  { name: 'Table Salt', aisle: 'spices_baking' },
  { name: 'Sea Salt', aisle: 'spices_baking' },
  { name: 'Kosher Salt', aisle: 'spices_baking' },
  { name: 'Himalayan Pink Salt', aisle: 'spices_baking' },
  { name: 'Black Pepper', aisle: 'spices_baking' },
  { name: 'Ground Black Pepper', aisle: 'spices_baking' },
  { name: 'Whole Peppercorns', aisle: 'spices_baking' },
  { name: 'White Pepper', aisle: 'spices_baking' },
  { name: 'Cayenne Pepper', aisle: 'spices_baking' },
  { name: 'Red Pepper Flakes', aisle: 'spices_baking' },
  { name: 'Paprika', aisle: 'spices_baking' },
  { name: 'Smoked Paprika', aisle: 'spices_baking' },
  { name: 'Hungarian Paprika', aisle: 'spices_baking' },
  { name: 'Chili Powder', aisle: 'spices_baking' },
  { name: 'Cumin', aisle: 'spices_baking' },
  { name: 'Ground Cumin', aisle: 'spices_baking' },
  { name: 'Cumin Seeds', aisle: 'spices_baking' },
  { name: 'Coriander', aisle: 'spices_baking' },
  { name: 'Ground Coriander', aisle: 'spices_baking' },
  { name: 'Turmeric', aisle: 'spices_baking' },
  { name: 'Curry Powder', aisle: 'spices_baking' },
  { name: 'Garam Masala', aisle: 'spices_baking' },
  { name: 'Cinnamon', aisle: 'spices_baking' },
  { name: 'Ground Cinnamon', aisle: 'spices_baking' },
  { name: 'Cinnamon Sticks', aisle: 'spices_baking' },
  { name: 'Nutmeg', aisle: 'spices_baking' },
  { name: 'Ground Nutmeg', aisle: 'spices_baking' },
  { name: 'Whole Nutmeg', aisle: 'spices_baking' },
  { name: 'Cloves', aisle: 'spices_baking' },
  { name: 'Ground Cloves', aisle: 'spices_baking' },
  { name: 'Whole Cloves', aisle: 'spices_baking' },
  { name: 'Allspice', aisle: 'spices_baking' },
  { name: 'Ginger', aisle: 'spices_baking' },
  { name: 'Ground Ginger', aisle: 'spices_baking' },
  { name: 'Cardamom', aisle: 'spices_baking' },
  { name: 'Ground Cardamom', aisle: 'spices_baking' },
  { name: 'Cardamom Pods', aisle: 'spices_baking' },
  { name: 'Star Anise', aisle: 'spices_baking' },
  { name: 'Fennel Seeds', aisle: 'spices_baking' },
  { name: 'Caraway Seeds', aisle: 'spices_baking' },
  { name: 'Mustard Seeds', aisle: 'spices_baking' },
  { name: 'Celery Salt', aisle: 'spices_baking' },
  { name: 'Celery Seed', aisle: 'spices_baking' },
  { name: 'Onion Powder', aisle: 'spices_baking' },
  { name: 'Garlic Powder', aisle: 'spices_baking' },
  { name: 'Garlic Salt', aisle: 'spices_baking' },
  { name: 'Minced Garlic', aisle: 'spices_baking' },
  { name: 'Dried Oregano', aisle: 'spices_baking' },
  { name: 'Dried Basil', aisle: 'spices_baking' },
  { name: 'Dried Thyme', aisle: 'spices_baking' },
  { name: 'Dried Rosemary', aisle: 'spices_baking' },
  { name: 'Dried Parsley', aisle: 'spices_baking' },
  { name: 'Dried Dill', aisle: 'spices_baking' },
  { name: 'Dried Sage', aisle: 'spices_baking' },
  { name: 'Bay Leaves', aisle: 'spices_baking' },
  { name: 'Italian Seasoning', aisle: 'spices_baking' },
  { name: 'Herbs de Provence', aisle: 'spices_baking' },
  { name: 'Poultry Seasoning', aisle: 'spices_baking' },
  { name: 'Taco Seasoning', aisle: 'spices_baking' },
  { name: 'Cajun Seasoning', aisle: 'spices_baking' },
  { name: 'Old Bay Seasoning', aisle: 'spices_baking' },
  { name: 'Everything Bagel Seasoning', aisle: 'spices_baking' },
  { name: 'Lemon Pepper', aisle: 'spices_baking' },
  { name: 'Seasoned Salt', aisle: 'spices_baking' },
  { name: 'Saffron', aisle: 'spices_baking' },
  { name: 'Vanilla Extract', aisle: 'spices_baking' },
  { name: 'Almond Extract', aisle: 'spices_baking' },
  { name: 'Peppermint Extract', aisle: 'spices_baking' },
  { name: 'Lemon Extract', aisle: 'spices_baking' },
  { name: 'All-Purpose Flour', aisle: 'spices_baking' },
  { name: 'Bread Flour', aisle: 'spices_baking' },
  { name: 'Cake Flour', aisle: 'spices_baking' },
  { name: 'Self-Rising Flour', aisle: 'spices_baking' },
  { name: 'Whole Wheat Flour', aisle: 'spices_baking' },
  { name: 'Almond Flour', aisle: 'spices_baking' },
  { name: 'Coconut Flour', aisle: 'spices_baking' },
  { name: 'Cornmeal', aisle: 'spices_baking' },
  { name: 'Cornstarch', aisle: 'spices_baking' },
  { name: 'Tapioca Starch', aisle: 'spices_baking' },
  { name: 'Arrowroot', aisle: 'spices_baking' },
  { name: 'Granulated Sugar', aisle: 'spices_baking' },
  { name: 'Brown Sugar', aisle: 'spices_baking' },
  { name: 'Light Brown Sugar', aisle: 'spices_baking' },
  { name: 'Dark Brown Sugar', aisle: 'spices_baking' },
  { name: 'Powdered Sugar', aisle: 'spices_baking' },
  { name: 'Confectioners Sugar', aisle: 'spices_baking' },
  { name: 'Coconut Sugar', aisle: 'spices_baking' },
  { name: 'Stevia', aisle: 'spices_baking' },
  { name: 'Splenda', aisle: 'spices_baking' },
  { name: 'Baking Soda', aisle: 'spices_baking' },
  { name: 'Baking Powder', aisle: 'spices_baking' },
  { name: 'Cream of Tartar', aisle: 'spices_baking' },
  { name: 'Active Dry Yeast', aisle: 'spices_baking' },
  { name: 'Instant Yeast', aisle: 'spices_baking' },
  { name: 'Gelatin', aisle: 'spices_baking' },
  { name: 'Cocoa Powder', aisle: 'spices_baking' },
  { name: 'Unsweetened Cocoa', aisle: 'spices_baking' },
  { name: 'Dutch Process Cocoa', aisle: 'spices_baking' },
  { name: 'Baking Chocolate', aisle: 'spices_baking' },
  { name: 'Semi-Sweet Chocolate Chips', aisle: 'spices_baking' },
  { name: 'Shredded Coconut', aisle: 'spices_baking' },
  { name: 'Sweetened Shredded Coconut', aisle: 'spices_baking' },
  { name: 'Flaked Coconut', aisle: 'spices_baking' },
  { name: 'Sprinkles', aisle: 'spices_baking' },
  { name: 'Food Coloring', aisle: 'spices_baking' },
  { name: 'Cake Mix', aisle: 'spices_baking' },
  { name: 'Brownie Mix', aisle: 'spices_baking' },
  { name: 'Pancake Mix', aisle: 'spices_baking' },
  { name: 'Muffin Mix', aisle: 'spices_baking' },
  { name: 'Frosting', aisle: 'spices_baking' },

  { name: 'Paper Towels', aisle: 'household' },
  { name: 'Toilet Paper', aisle: 'household' },
  { name: 'Facial Tissues', aisle: 'household' },
  { name: 'Napkins', aisle: 'household' },
  { name: 'Paper Plates', aisle: 'household' },
  { name: 'Paper Cups', aisle: 'household' },
  { name: 'Plastic Cups', aisle: 'household' },
  { name: 'Plastic Utensils', aisle: 'household' },
  { name: 'Plastic Wrap', aisle: 'household' },
  { name: 'Aluminum Foil', aisle: 'household' },
  { name: 'Parchment Paper', aisle: 'household' },
  { name: 'Wax Paper', aisle: 'household' },
  { name: 'Zip Lock Bags', aisle: 'household' },
  { name: 'Sandwich Bags', aisle: 'household' },
  { name: 'Freezer Bags', aisle: 'household' },
  { name: 'Trash Bags', aisle: 'household' },
  { name: 'Kitchen Trash Bags', aisle: 'household' },
  { name: 'Dish Soap', aisle: 'household' },
  { name: 'Dishwasher Detergent', aisle: 'household' },
  { name: 'Dishwasher Pods', aisle: 'household' },
  { name: 'Rinse Aid', aisle: 'household' },
  { name: 'Sponges', aisle: 'household' },
  { name: 'Scrub Brushes', aisle: 'household' },
  { name: 'Steel Wool', aisle: 'household' },
  { name: 'All-Purpose Cleaner', aisle: 'household' },
  { name: 'Glass Cleaner', aisle: 'household' },
  { name: 'Disinfecting Wipes', aisle: 'household' },
  { name: 'Bleach', aisle: 'household' },
  { name: 'Laundry Detergent', aisle: 'household' },
  { name: 'Fabric Softener', aisle: 'household' },
  { name: 'Dryer Sheets', aisle: 'household' },
  { name: 'Stain Remover', aisle: 'household' },
  { name: 'Air Freshener', aisle: 'household' },
  { name: 'Candles', aisle: 'household' },
  { name: 'Matches', aisle: 'household' },
  { name: 'Lighter', aisle: 'household' },
  { name: 'Light Bulbs', aisle: 'household' },
  { name: 'Batteries', aisle: 'household' },
  { name: 'AA Batteries', aisle: 'household' },
  { name: 'AAA Batteries', aisle: 'household' },

  { name: 'Shampoo', aisle: 'personal_care' },
  { name: 'Conditioner', aisle: 'personal_care' },
  { name: 'Body Wash', aisle: 'personal_care' },
  { name: 'Bar Soap', aisle: 'personal_care' },
  { name: 'Hand Soap', aisle: 'personal_care' },
  { name: 'Face Wash', aisle: 'personal_care' },
  { name: 'Toothpaste', aisle: 'personal_care' },
  { name: 'Toothbrush', aisle: 'personal_care' },
  { name: 'Mouthwash', aisle: 'personal_care' },
  { name: 'Dental Floss', aisle: 'personal_care' },
  { name: 'Deodorant', aisle: 'personal_care' },
  { name: 'Antiperspirant', aisle: 'personal_care' },
  { name: 'Lotion', aisle: 'personal_care' },
  { name: 'Body Lotion', aisle: 'personal_care' },
  { name: 'Hand Cream', aisle: 'personal_care' },
  { name: 'Sunscreen', aisle: 'personal_care' },
  { name: 'Lip Balm', aisle: 'personal_care' },
  { name: 'Razor Blades', aisle: 'personal_care' },
  { name: 'Disposable Razors', aisle: 'personal_care' },
  { name: 'Shaving Cream', aisle: 'personal_care' },
  { name: 'Aftershave', aisle: 'personal_care' },
  { name: 'Cotton Balls', aisle: 'personal_care' },
  { name: 'Cotton Swabs', aisle: 'personal_care' },
  { name: 'Q-Tips', aisle: 'personal_care' },
  { name: 'Band-Aids', aisle: 'personal_care' },
  { name: 'First Aid Kit', aisle: 'personal_care' },
  { name: 'Pain Reliever', aisle: 'personal_care' },
  { name: 'Ibuprofen', aisle: 'personal_care' },
  { name: 'Acetaminophen', aisle: 'personal_care' },
  { name: 'Aspirin', aisle: 'personal_care' },
  { name: 'Antacid', aisle: 'personal_care' },
  { name: 'Allergy Medicine', aisle: 'personal_care' },
  { name: 'Cold Medicine', aisle: 'personal_care' },
  { name: 'Cough Drops', aisle: 'personal_care' },
  { name: 'Vitamins', aisle: 'personal_care' },
  { name: 'Multivitamins', aisle: 'personal_care' },

  { name: 'Dog Food', aisle: 'pet_supplies' },
  { name: 'Dry Dog Food', aisle: 'pet_supplies' },
  { name: 'Wet Dog Food', aisle: 'pet_supplies' },
  { name: 'Dog Treats', aisle: 'pet_supplies' },
  { name: 'Dog Biscuits', aisle: 'pet_supplies' },
  { name: 'Puppy Food', aisle: 'pet_supplies' },
  { name: 'Cat Food', aisle: 'pet_supplies' },
  { name: 'Dry Cat Food', aisle: 'pet_supplies' },
  { name: 'Wet Cat Food', aisle: 'pet_supplies' },
  { name: 'Cat Treats', aisle: 'pet_supplies' },
  { name: 'Kitten Food', aisle: 'pet_supplies' },
  { name: 'Cat Litter', aisle: 'pet_supplies' },
  { name: 'Clumping Cat Litter', aisle: 'pet_supplies' },
  { name: 'Bird Seed', aisle: 'pet_supplies' },
  { name: 'Fish Food', aisle: 'pet_supplies' },
  { name: 'Hamster Food', aisle: 'pet_supplies' },
  { name: 'Rabbit Food', aisle: 'pet_supplies' },
  { name: 'Pet Shampoo', aisle: 'pet_supplies' },
  { name: 'Flea Treatment', aisle: 'pet_supplies' },
  { name: 'Poop Bags', aisle: 'pet_supplies' },
];
